class Stat:
    def __init__(self,
                 minionsKilled : float,
                 championsKilled : int,
                 numDeaths : int,
                 assists : int,
                 wardPlaced : int,
                 wardKilled : int,
                 visionScore : float,
                 totalDamageDealt : float,
                 totalDamageTaken : float,
                 totalDamageDealtChampions : float,
                 totalDamageSelfMitigated : float,
                 totalDamageShieldedOnTeammates : float,
                 totalDamageDealtToBuildings : float,
                 totalDamageDealtToObjectives : float,
                 totalTimeCrowdControlDealt : float,
                 totalTimeCCOthers : float):
        self.minionsKilled = minionsKilled
        self.championsKilled = championsKilled
        self.numDeaths = numDeaths
        self.assists = assists
        self.wardPlaced = wardPlaced
        self.wardKilled = wardKilled
        self.visionScore = visionScore
        self.totalDamageDealt = totalDamageDealt
        self.totalDamageTaken = totalDamageTaken
        self.totalDamageDealtChampions = totalDamageDealtChampions
        self.totalDamageSelfMitigated = totalDamageSelfMitigated
        self.totalDamageShieldedOnTeammates = totalDamageShieldedOnTeammates
        self.totalDamageDealtToBuildings = totalDamageDealtToBuildings
        self.totalDamageDealtToObjectives = totalDamageDealtToObjectives
        self.totalTimeCrowdControlDealt = totalTimeCrowdControlDealt
        self.totalTimeCCOthers = totalTimeCCOthers
