brute_data: "../data/"
save_path: "./saved_data"
serialized_path: "../data/"
match: "WBGvsT1"
split: 300,900
playersTeamOne:
  - "WBG Xiaohu"
  - "WBG Weiwei"
playersTeamTwo: 
  - "T1 Faker"
  - "T1 Oner"
