brute_data: ../data/
database_path: ../db/
match: 
- ESPORTSTMNT03_3227454
patch: 14.1.547.8890
playersTeamTwo:
- T1 Oner
playersTeamOne:
- JDG Kanavi
save_path: ./saved_data
serialized_path: ../data/
split: 90,540,900,1500
