brute_data: "../data/"
save_path: "./saved_data"
serialized_path: "../data/"
database_path: "../db/"

match: ESPORTSTMNT03_3222943
split: 90,540,900,1500

playersTeamOne: 
  - "T1 Oner"

playersTeamTwo:
  - "JDG Kanavi"
