brute_data: ../data/
database_path: ../db/
match:
- LOLTMNT99_132785
- LOLTMNT99_132720
- LOLTMNT99_131606
- LOLTMNT99_132509
- LOLTMNT99_132404
- LOLTMNT99_127783
- LOLTMNT99_126859
- LOLTMNT99_127543
- LOLTMNT99_126612
patch: '14.1'
playersTeamOne:
- WBG TheShy
playersTeamTwo:
- BLG Bin
save_path: ./saved_data
serialized_path: ../data/
split: 90,540,900,1500
