brute_data: ../data/
database_path: ../db/
match: LOLTMNT99_108522
playersTeamOne:
- T1 Oner
playersTeamTwo:
- JDG Kanavi
save_path: ./saved_data
serialized_path: ../data/
split: 90,540,900,1500
patch: "14.1.547.8890"
