brute_data: ../data/
database_path: ../db/
match:
- ESPORTSTMNT03_3225986
patch: 13.19.535.4316
playersTeamOne:
- WBG TheShy
playersTeamTwo:
- BLG Bin
save_path: ./saved_data
serialized_path: ../data/
split: 90,540,900,1500
